# Server Configuration
server:
  port: ${PORT:8085}

spring:
  profiles:
    active: prod
  application:
    name: transaction-ms
  config:
    import: optional:configserver:http://localhost:8888
  devtools:
    restart:
      enabled: true
  data:
    rest:
      base-path: /api